name: Code style and static analysis

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          extensions: dom, curl, libxml, mbstring, zip
          coverage: none
          php-version: '7.4'

      - name: Install dependencies
        run: composer update --no-progress --no-interaction --prefer-dist

      - name: Run script
        run: composer test:style
